name: Railway Backup
on:
  workflow_dispatch:  # 手动触发
  schedule:
    - cron: '0 2 * * *'  # 每天凌晨2点自动备份

jobs:
  backup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          
      - name: Install Railway CLI
        run: |
          npm install -g @railway/cli
          railway --version
          
      - name: Check Railway CLI installation
        run: |
          which railway
          railway --version
          echo "Railway CLI installed successfully"
          
      - name: Login to Railway
        run: |
          echo "Attempting to login to Railway..."
          echo ${{ secrets.RAILWAY_TOKEN }} | railway login
          echo "Login completed"
          
      - name: Check Railway login status
        run: |
          echo "Checking Railway login status..."
          railway whoami
          echo "Login status checked"
          
      - name: Link to Railway project
        run: |
          echo "Linking to Railway project: ${{ secrets.RAILWAY_PROJECT_ID }}"
          railway link --project ${{ secrets.RAILWAY_PROJECT_ID }}
          echo "Project linked successfully"
          
      - name: Check Railway project status
        run: |
          echo "Checking Railway project status..."
          railway status
          echo "Project status checked"
          
      - name: List current directory
        run: |
          echo "Current directory contents:"
          ls -la
          echo "Directory listing completed"
          
      - name: Check if backup script exists
        run: |
          echo "Checking for backup script..."
          if [ -f "railway_backup_correct.py" ]; then
            echo "Backup script found: railway_backup_correct.py"
            ls -la railway_backup_correct.py
          else
            echo "Backup script NOT found!"
            echo "Available Python files:"
            find . -name "*.py" -type f
          fi
          
      - name: Run backup script
        run: |
          echo "Starting backup process..."
          railway run python railway_backup_correct.py
          echo "Backup script execution completed"
          
      - name: Wait for backup completion
        run: |
          echo "Waiting for backup to complete..."
          sleep 15
          echo "Wait completed"
          
      - name: List backup files
        run: |
          echo "Checking for backup files..."
          ls -la *.zip || echo "No zip files found"
          echo "File listing completed"
          
      - name: Check backup file size
        run: |
          if [ -f "railway_backup_*.zip" ]; then
            echo "Backup file found:"
            ls -la railway_backup_*.zip
            echo "File size check completed"
          else
            echo "No backup zip files found"
          fi
          
      - name: Create GitHub Release
        if: success() && contains(steps.list-backup-files.outputs.files, '*.zip')
        uses: softprops/action-gh-release@v1
        with:
          files: railway_backup_*.zip
          tag_name: backup-${{ github.run_number }}
          name: Railway Backup ${{ github.run_number }}
          body: |
            ## Railway数据备份
            
            **备份时间**: ${{ github.event.head_commit.timestamp }}
            **触发方式**: ${{ github.event_name }}
            **工作流运行**: #${{ github.run_number }}
            
            ### 备份内容
            - 用户自定义币种
            - 数据库文件
            - 缓存目录
            - 日志文件
            
            ### 使用方法
            1. 下载ZIP文件
            2. 解压到本地目录
            3. 使用恢复脚本恢复数据
            
            **注意**: 此备份包含敏感数据，请妥善保管
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Upload backup as artifact
        uses: actions/upload-artifact@v4
        with:
          name: railway-backup-${{ github.run_number }}
          path: railway_backup_*.zip
          retention-days: 30
          if-no-files-found: warn
